# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
        ('bin\\cgfs16_overlay.dll',   'bin'),
        ('bin\\cgfs16_inject.exe',    'bin'),
        ('bin\\FifaLibrary16.dll',    'bin'),
        ('bin\\KitExtractorHost.exe', 'bin'),
        ('bin\\un_chunlzma.exe',      'bin'),
        ('bin\\fifa16_decryptor.exe', 'bin'),
        ('bin\\zlib.net.dll',        'bin'),
    ],
    datas=[
        ('server16_py\\offsets.json', 'server16_py'),
        ('server16_py\\bh_worker.py', 'server16_py'),
        ('server16_py\\db_worker.py', 'server16_py'),
        ('server16_py\\kit_worker.py', 'server16_py'),
        ('server16_py\\kit_preview_worker.py', 'server16_py'),
        ('server16_py\\dds_image_worker.py', 'server16_py'),
        ('server16_py\\locales', 'server16_py\\locales'),
        ('bin\\python32', 'bin\\python32'),
        ('bin\\Templates', 'bin\\Templates'),
        ('server16.ico', '.'),
        ('install_data', 'install_data'),
        ('resources', 'resources'),
    ],
    hiddenimports=['clr', 'rarfile'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Server16Python',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['server16.ico'],
)
