######################################
##     CG Server 16 Python port     ##
######################################

[stadium]

[stadiumnetid]

[chantsid]

[scoreboard]

[scoreboardstdname]

[scoreboardstdnamem]

[hometeamscoreboard]

[TVLogo]

[hometeamtvlogo]

[movies]

[derbymatch]

[TeamMovies]

[modules]
Autorun=0
ScoreBoard=1
Stadium=1
StadiumNet=1
Movies=1
TvLogo=1
Chants=1
AwayClubSong=1
AwayChants=1
StadiumName=1
DiscordRPC=1
